# Generated by Django 5.0.1 on 2024-01-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('applicant', 'Applicant')], default='applicant', max_length=100),
        ),
    ]
